name: Build Next.js 13 App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn build
